server:
  port: 8081
resource:
  device:
    devices: http://localhost:8080/device/devices
    device: http://localhost:8080/device/{id}
    search: http://localhost:8080/device/search
    create: http://localhost:8080/device/save
    connect: http://localhost:8080/device/connect/{deviceId}
    saveData: http://localhost:8080/device/connect/saveData/{deviceId}
    remove: http://localhost:8080/device/{id}
    connectedDevices: http://localhost:8080/device/connectedDevices
    deviceNames: http://localhost:8080/device/deviceNames
  map:
    refreshData: http://localhost:8080/map/refreshData
    encoderData: http://localhost:8080/map/encoderData/{selectedDevice}
